Source/Jobs/Controllers/SaleDeliveryWizardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Core.Common;
using Model.Models;
using Data.Models;
using Model.ViewModels;
using Service;
using Jobs.Helpers;
using Data.Infrastructure;
using System.Web.UI.WebControls;
using AutoMapper;
using Microsoft.AspNet.Identity;
using System.Configuration;
using Presentation;
using Model.ViewModel;
using Reports.Controllers;



namespace Jobs.Controllers
{
    [Authorize]
    public class SaleDeliveryWizardController : System.Web.Mvc.Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        List<string> UserRoles = new List<string>();
        ActiivtyLogViewModel LogVm = new ActiivtyLogViewModel();

        ISaleDeliveryHeaderService _SaleDeliveryHeaderService;
        IUnitOfWork _unitOfWork;
        IExceptionHandlingService _exception;

        public SaleDeliveryWizardController(ISaleDeliveryHeaderService PurchaseOrderHeaderService, IUnitOfWork unitOfWork, IExceptionHandlingService exec)
        {
            _SaleDeliveryHeaderService = PurchaseOrderHeaderService;
            _exception = exec;
            _unitOfWork = unitOfWork;

            UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];

            //Log Initialization
            LogVm.SessionId = 0;
            LogVm.ControllerName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
            LogVm.ActionName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
            LogVm.User = System.Web.HttpContext.Current.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        public ActionResult CreateSaleDelivery(int id)//DocTypeId
        {

            int DivisionId = (int)System.Web.HttpContext.Current.Session["DivisionId"];
            int SiteId = (int)System.Web.HttpContext.Current.Session["SiteId"];
            List<string> UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];
            ViewBag.id = id;

            int DocTypeId = id;

            //Getting Settings
            var settings = new SaleDeliverySettingService(_unitOfWork).GetSaleDeliverySettingForDocument(DocTypeId, DivisionId, SiteId);

            if (settings == null && UserRoles.Contains("SysAdmin"))
            {
                return RedirectToAction("Create", "SaleDeliverySettings", new { id = DocTypeId }).Warning("Please create settings");
            }
            else if (settings == null && !UserRoles.Contains("SysAdmin"))
            {
                return View("~/Views/Shared/InValidSettings.cshtml");
            }

            return View("CreateSaleDelivery");
        }

        public JsonResult PendingSaleInvoice(int id)//DocTypeId
        {

            var temp = _SaleDeliveryHeaderService.GetSaleInvoiceForSaleDeliveryWizard(id).ToList();

            return Json(new { data = temp }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ConfirmSaleInvoiceList(List<SaleDeliveryWizardViewModel> Selected, int id)
        {
            int DivisionId = (int)System.Web.HttpContext.Current.Session["DivisionId"];
            int SiteId = (int)System.Web.HttpContext.Current.Session["SiteId"];
            var settings = new SaleDeliverySettingService(_unitOfWork).GetSaleDeliverySettingForDocument(id, DivisionId, SiteId);

            System.Web.HttpContext.Current.Session["PendingInvoiceForSaleDelivery"] = Selected;

            return Json(new { Success = "URL", Data = "/SaleDeliveryWizard/Create/" + id.ToString() }, JsonRequestBehavior.AllowGet);
        }

        [Serializable]
        public class SelectedSaleInvoice
        {
            public int id { get; set; }
            public decimal Qty { get; set; }
            public int? RefDocTypeId { get; set; }
            public int? RefDocLineId { get; set; }
        }

        private void PrepareViewBag()
        {
            ViewBag.UnitConvForList = (from p in db.UnitConversonFor
                                       select p).ToList();
            ViewBag.DeliveryUnitList = new UnitService(_unitOfWork).GetUnitList().ToList();
        }


        // GET: /SaleDeliveryHeader/Create

        public ActionResult Create(int id)//DocumentTypeId
        {
            SaleDeliveryHeaderViewModel p = new SaleDeliveryHeaderViewModel();

            p.DocDate = DateTime.Now;
            p.CreatedDate = DateTime.Now;

            p.DivisionId = (int)System.Web.HttpContext.Current.Session["DivisionId"];
            p.SiteId = (int)System.Web.HttpContext.Current.Session["SiteId"];
            List<string> UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];

            int DocTypeId = id;

            //Getting Settings
            var settings = new SaleDeliverySettingService(_unitOfWork).GetSaleDeliverySettingForDocument(DocTypeId, p.DivisionId, p.SiteId);

            if (settings == null && UserRoles.Contains("SysAdmin"))
            {
                return RedirectToAction("Create", "SaleDeliverySettings", new { id = DocTypeId }).Warning("Please create job order settings");
            }
            else if (settings == null && !UserRoles.Contains("SysAdmin"))
            {
                return View("~/Views/Shared/InValidSettings.cshtml");
            }
            p.SaleDeliverySettings = Mapper.Map<SaleDeliverySetting, SaleDeliverySettingsViewModel>(settings);

            
            p.ProcessId = settings.ProcessId;
            PrepareViewBag();
            p.DocTypeId = DocTypeId;
            p.DocNo = new DocumentTypeService(_unitOfWork).FGetNewDocNo("DocNo", ConfigurationManager.AppSettings["DataBaseSchema"] + ".SaleDeliveryHeaders", p.DocTypeId, p.DocDate, p.DivisionId, p.SiteId);

            //RatesFetching from RateList Master
            var Lines = (List<SaleDeliveryWizardViewModel>)System.Web.HttpContext.Current.Session["PendingInvoiceForSaleDelivery"];
            if (Lines != null)
            {
                if (Lines.FirstOrDefault().SaleToBuyerId != null)
                {
                    p.SaleToBuyerId = (int)Lines.FirstOrDefault().SaleToBuyerId;
                    var PersonAddress = new PersonAddressService(_unitOfWork).GetShipAddressByPersonId(p.SaleToBuyerId);
                    if (PersonAddress != null)
                    {
                        p.ShipToPartyAddress = PersonAddress.Address;
                    }
                }
            }


            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Post(SaleDeliveryHeaderViewModel svm)
        {
            bool TimePlanValidation = true;
            string ExceptionMsg = "";
            bool Continue = true;

            SaleDeliveryHeader s = Mapper.Map<SaleDeliveryHeaderViewModel, SaleDeliveryHeader>(svm);
            List<SaleDeliveryWizardViewModel> SaleInvoiceAndQtys = (List<SaleDeliveryWizardViewModel>)System.Web.HttpContext.Current.Session["PendingInvoiceForSaleDelivery"];
            if (svm.SaleDeliverySettings != null)
            {
                //if (svm.SaleDeliverySettings.isMandatoryCostCenter == true && (string.IsNullOrEmpty(svm.CostCenterName)))
                //{
                //    ModelState.AddModelError("CostCenterName", "The CostCenter field is required");
                //}
            }



            if (SaleInvoiceAndQtys.Count() <= 0)
                ModelState.AddModelError("", "No Records Selected");

            int SaleToBuyerCnt = (from l in SaleInvoiceAndQtys
                                group l by l.SaleToBuyerId into g
                                select new
                                {
                                    SaleToBuyerId = g.Key,
                                }).Distinct().Count();

            if (SaleToBuyerCnt > 1)
                ModelState.AddModelError("", "Select any one Buyer Orders.");

            List<SaleDeliveryLine> BarCodesToUpdate = new List<SaleDeliveryLine>();

            bool CostCenterGenerated = false;

            #region DocTypeTimeLineValidation

            try
            {

                if (svm.SaleDeliveryHeaderId <= 0)
                    TimePlanValidation = DocumentValidation.ValidateDocument(Mapper.Map<DocumentUniqueId>(svm), DocumentTimePlanTypeConstants.Create, User.Identity.Name, out ExceptionMsg, out Continue);
                else
                    TimePlanValidation = DocumentValidation.ValidateDocument(Mapper.Map<DocumentUniqueId>(svm), DocumentTimePlanTypeConstants.Modify, User.Identity.Name, out ExceptionMsg, out Continue);

            }
            catch (Exception ex)
            {
                string message = _exception.HandleException(ex);
                TempData["CSEXC"] += message;
                TimePlanValidation = false;
            }

            if (!TimePlanValidation)
                TempData["CSEXC"] += ExceptionMsg;

            #endregion

            if (ModelState.IsValid && (TimePlanValidation || Continue))
            {

                if (svm.SaleDeliveryHeaderId <= 0)
                {


                    if (SaleInvoiceAndQtys.Count() > 0)
                    {
                        s.CreatedDate = DateTime.Now;
                        s.ModifiedDate = DateTime.Now;
                        s.CreatedBy = User.Identity.Name;
                        s.ModifiedBy = User.Identity.Name;
                        s.Status = (int)StatusConstants.Drafted;
                        _SaleDeliveryHeaderService.Create(s);


                        int Cnt = 0;
                        int Sr = 0;

                        int pk = 0;

                        SaleDeliverySetting Settings = new SaleDeliverySettingService(_unitOfWork).GetSaleDeliverySettingForDocument(s.DocTypeId, s.DivisionId, s.SiteId);

Source/Jobs/Views/SaleDeliveryWizard/Create.cshtml
@model Model.ViewModels.SaleDeliveryHeaderViewModel
@using Core.Common
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


@using (Html.BeginForm("Post", "SaleDeliveryWizard", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.SiteId)
    @Html.HiddenFor(m => m.Status)
    @Html.HiddenFor(m => m.DivisionId)
    @Html.HiddenFor(m => m.SaleDeliveryHeaderId)
    @Html.HiddenFor(m => m.DocTypeId)
    @Html.HiddenFor(m => m.CreatedDate)
    @Html.HiddenFor(m => m.ProcessId)

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 style="border-bottom:0px solid #e1dada;padding-bottom:0px;">
                <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"> <span class="glyphicon glyphicon-file black"></span> Sale Delivery Details</span>
                <input type="submit" value="Save" class="btn btn-primary right" id="submit" style="width: 90px; background-color: #2980b9" />
            </h3>
            <hr style="margin-top:0px;margin-bottom:0px" />
        </div>


        <div class="panel-info" style="padding-left:15px">
            <div class="form-horizontal">
                @Html.ValidationSummary(true)
                <div class="row">
                    <h4 class="col-md-12 black">
                        <span class="glyphicon glyphicon-align-justify"></span>
                        1.Document Details
                    </h4>
                    <div>
                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group" style="margin-top:15px">
                                    @Html.LabelFor(model => model.DocDate, "Delivery Date", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextBoxFor(m => m.DocDate, "{0:dd/MMMM/yyyy}", new { @class = "datepickerWithNFD form-control col-xs-6 required" })
                                        @Html.ValidationMessageFor(model => model.DocDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group" style="margin-top:15px">
                                    @Html.LabelFor(model => model.DocNo, "Delivery No", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextBoxFor(m => m.DocNo, null, new { @class = "form-control col-xs-6 required" })
                                        @Html.ValidationMessageFor(m => m.DocNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            

                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.SaleToBuyerId, "Party", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextBoxFor(m => m.SaleToBuyerId, new { @class = "form-control col-xs-6 ", @readonly = "true" })
                                        @Html.ValidationMessageFor(model => model.SaleToBuyerId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DeliverToPerson, "Deliver To Person", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextBoxFor(m => m.DeliverToPerson, new { @class = "form-control col-xs-6 " })
                                        @Html.ValidationMessageFor(model => model.DeliverToPerson, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DeliverToPersonReference, "Relation With Person", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextBoxFor(m => m.DeliverToPersonReference, new { @class = "form-control col-xs-6 " })
                                        @Html.ValidationMessageFor(model => model.DeliverToPersonReference, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ShipToPartyAddress, "Delivery Address", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextAreaFor(m => m.ShipToPartyAddress, new { @class = "form-control col-xs-6" })
                                        @Html.ValidationMessageFor(m => m.ShipToPartyAddress, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Remark, "Remark", new { @class = "control-label col-xs-4" })
                                    <div class="col-xs-6">
                                        @Html.TextAreaFor(m => m.Remark, new { @class = "form-control col-xs-6" })
                                        @Html.ValidationMessageFor(m => m.Remark, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">

        $(document).ready(function () {
            CustomSelectFunction($("#SaleToBuyerId"), '/SaleDeliveryHeader/GetCustomPerson', '/ComboHelpList/SetSinglePerson', ' ', false, 0,$('#DocTypeId').val());
        });


        var IsSaved=false;
        var ValidationCount=0;

        $('form').submit(function(event){

            if(!IsSaved)
            {
                if(!ValidateData() || !ValidateCostCenter())
                {
                    return false;
                }
                IsSaved=true;
                return IsSaved;
            }
            else
            {
                return false;
            }


        });


        function ValidateData() {
            var DocId=@Model.SaleDeliveryHeaderId;
            var TempValue;
            var ValidationMessage="";



            //Checking for dulicate key value
            if(DocId<=0)
            {
                TempValue= $('#DocNo').DuplicateCheckForCreate({ name: 'JobOrders', value: $('#DocNo').val(), doctype: $('#DocTypeId').val() });
                if (TempValue){ ValidationMessage=$('#DocNo').val() + " already exist <br />";}
            }
            else
            {
                TempValue = $('#DocNo').DuplicateCheckForEdit({ name: 'JobOrders', value: $('#DocNo').val(), doctype: $('#DocTypeId').val(),headerId:DocId });
                if (TempValue) {ValidationMessage+=$('#DocNo').val() + " already exist <br />";}
            }
            if(TempValue)
            {
                if($('#validationerrormsg').length==0){
                    $('.panel-info').filter(':eq(1)').before('<div class="alert alert-danger" role="alert" id="validationerrormsg">'+ValidationMessage+'</div>');}
                else
                {
                    $('#validationerrormsg').html(ValidationMessage);
                }
            }


            return  (ValidationMessage=="");

        }

</script>

Source/Jobs/Views/SaleDeliveryWizard/CreateSaleDelivery.cshtml
@{
    ViewBag.Title = "Sale Delivery Wizard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.scroller.js"></script>*@
<script src="~/Scripts/DataTables/dataTables.scroller.min.js"></script>

<style type="text/css">
    .DTHidden {
        display: none;
    }

    .TextRight {
        text-align: right;
    }

    .dataTables_scroll {
        font-size: 13px !important;
        line-height: 1;
    }

    table.dataTable tbody td {
        padding: 2px 10px;
    }
</style>



@*<input type="button" id="button" />*@
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-list black"></span> Pending Sale Invoice List</span>
            @Html.ActionLink(" ", "ConfirmSaleInvoiceList", "SaleDeliveryWizard", null, new { @class = "glyphicon glyphicon-hand-right toolbar right", @title = "Proceed", @data_toggle = "tooltip", @id = "Proceed" })
            @*<a href="#" class="glyphicon glyphicon-shopping-cart toolbar right" id="CartSum"></a>*@
        </h3>
        <span id="Validation" class="danger"></span>
        <hr style="margin-top:0px;margin-bottom:0px" />
    </div>



    <div class="panel-info tab" style="padding-left:5px;padding-top:20px">
        @*<input type="checkbox" id="TestCheck" name="checl" /> <span>Select</span>*@
        <table id="example" class="display" cellspacing="0" width="100%">
            <thead style="background: #428bca;color:white">
                <tr>
                    <th>Invoice No</th>
                    <th>Invoice Date</th>
                    <th>SaleToBuyerId</th>
                    <th>Buyer Name</th>
                    <th>Qty</th>
                    <th>Amount</th>
                    <th>SaleInvoiceLineId</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th></th>
                    <th colspan="0" style="text-align:left"></th>
                    <th colspan="1" style="text-align:right"></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {

        var PageLoadFirst = true;
        var Url = "/SaleDeliveryWizard/PendingSaleInvoice/" + '@ViewBag.id';
        $('#example').dataTable({
            ajax: Url,
            scrollY: "300px",
            scrollCollapse: false,
            scroller: true,
            sort : false,
            lengthChange : false,
            bInfo: false,
            columns: [
                { "data": "DocNo", "width": "10%" },
                { "data": "Date", "width": "10%" },
                { "data": "SaleToBuyerId", "width": "10%" },
                { "data": "SaleToBuyerName", "width": "10%" },
                { "data": "Qty", "width": "5%", className: "TextRight", },
                { "data": "Amount", "width": "5%", className: "TextRight", },
                { "data": "SaleInvoiceLineId" },
            ],
            columnDefs: [
    { "targets": 2, "searchable": false, className: "DTHidden", },
    { "targets": 6, "searchable": false, className: "DTHidden", },
            ],
            dom: 'T<"clear">lfrti',
            TableTools: {
                "sRowSelect": "os",
                "aButtons": [
                "select_all", "select_none"
                ]
            },
            tableTools: {
                "sSwfPath": "../../Content/DataTables/swf/copy_csv_xls_pdf.swf"
            }


        });

        $('#example tbody').on('click', 'tr', function (e) {
            if (e.target.nodeName == "INPUT") {

            }
            else {
                $(this).toggleClass('selected');

                if (PageLoadFirst) {
                    CaclTotal();
                    PageLoadFirst = false;
                }

                if ($(this).hasClass('selected') && !$('#TestCheck').is(':checked')) {
                    $('#TestCheck').prop("checked", true);
                }

                CalculateSelectedTotal();
            }
        });

        var id = @ViewBag.id;
        $('a#Proceed').click(function () {
            var arr = [];

            var table = $("#example").DataTable();
            var test = table.rows('.selected').data();
            var List = "";
            var test34 = table.$('input, select').serialize();
            $.each(test, function (index, value) {
                arr.push({ SaleInvoiceLineId: value.SaleInvoiceLineId, Qty: value.Qty, Amount: value.Amount, SaleToBuyerId: value.SaleToBuyerId });
            })


            //alert($(this).attr('href'));
            var ValidationMsg = "";

            for (var i = 0; i < test.length; i++) {
                if (i > 0)
                {
                    if (test[i].SaleToBuyerId != test[i-1].SaleToBuyerId)
                    {
                        ValidationMsg = "More then one Buyers can not be selected.";
                    }
                }
            }

            if (ValidationMsg != "")
            {
                $("#Validation").text(ValidationMsg);
                return false;
            }

            
            $.ajax({
                url: $(this).attr('href'),
                type: "POST",
                data: { Selected: arr, id: id },
                success: function (result) {
                    if (result.Success == true) {
                        UpdateDataTable(result);
                    } else if (result.Success == "URL") {
                        window.location.href = result.Data;
                    }
                    else if (!result.Success) {
                        alert('Something went wrong');
                    }
                    else { }
                },
            });

            return false;

        });

        function UpdateDataTable(data) {
            var table = $('#example').DataTable();

            table.clear().draw();

            table.rows.add(data.Data).draw();

            $('#example').dataTable().fnFilterClear();

            $('tfoot > tr > th:first').html('');

            UpdateActionLink();

        }

        function UpdateActionLink() {
            $('a#Proceed').attr('href', '/SaleDeliveryWizard/ConfirmSaleInvoiceList');
        }

        $(document).on('change', 'td > input', function () {
            var table = $('#example').dataTable();
            var td = $(this).closest('td').get(0);
            var pos = table.fnGetPosition(td); // Im not familiar with the plugin so the extra $() might be overkill

            if ($(this).is('.Qty') && table.fnGetData(pos[0]).BalanceQty < $(this).val()) {
                $(this).val(table.fnGetData(pos[0]).BalanceQty).select();
            }
            else {
                table.fnUpdate(parseFloat($(this).val()), pos[0], pos[1], false);
                $('#example').DataTable().draw(false);
                CalculateSelectedTotal();
            }
        })


        function CaclTotal() {
            var table = $('#example').DataTable();

            var intVal = function (i) {
                return typeof i === 'string' ?
                    i.replace(/[\$,]/g, '') * 1 :
                    typeof i === 'number' ?
                    i : 0;
            };

            // Total over all pages
            total = table
                .column(7)
                .data()
                .reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0);

            totalArea = table
               .column(8)
               .data()
               .reduce(function (a, b) {
                   return intVal(a) + intVal(b);
               }, 0);

            //$(table.column(5).footer()).html(
            //           'Total: ' + total.toFixed(0) + ' Pcs, ' + totalArea.toFixed(3) + ' Sq.yard'
            //     );


        }

    });


    $('#TestCheck').change(function () {

        var table = $('#example').dataTable();
        var $LRow;


        if ($(this).is(':checked')) {
            var Rows = table.$('tr', { "filter": "applied" })
            $.each(Rows, function (index, value) {

                $(this).addClass('selected');
                $LRow = this;
            })
            CalculateSelectedTotal();
        }
        else {
            var Rows = table.$('tr.selected')
            $.each(Rows, function (index, value) {

                $(this).removeClass('selected');
                $LRow = this;

            })
            CalculateSelectedTotal();
        }

    })


    function CalculateSelectedTotal() {
        var table = $('#example').DataTable();

        function CheckTotal() {
            var Qty = 0;
            $.each(table.rows('.selected').data(), function (index, value) {
                Qty += parseFloat(value.Qty);
            })
            return Qty.toFixed(0);
        }
        function CheckTotalArea() {
            var Qty = 0;
            $.each(table.rows('.selected').data(), function (index, value) {
                Qty += parseFloat(value.Area);
            })
            return Qty.toFixed(3);
        }

        $(table.column(1).footer()).html(
                'Selected:' + CheckTotal() + ' Pcs, ' + CheckTotalArea() + ' Sq.yards'
           );



    }



    function ResetTotal() {
        var table = $('#example').DataTable();
        $(table.column(1).footer()).html(
                    'Selected:' + 0 + ' Pcs '
               );
    }

    $('#CartSum').click(function () {
        GenerateSummaryString();
        $('#exampleModal').modal('toggle');
    })


    function GenerateSummaryString() {
        var Summary = "";
        Summary += "<div class='row' style='margin:0px'>"

        var table = $("#example").DataTable();
        var test = table.rows('.selected').data();
        var List = "";
        var srno = 1;
        var test34 = table.$('input, select').serialize();
        var QtyTotal = 0;
        var AmtTotal = 0;
        $.each(test, function (index, value) {

            Summary += " <div class='row crow grid-body' style='margin:0px;padding:0px'>"
                + "      <div class='row-index block'  style='width:5%'>" + srno + "</div>"
                + "          <div class='block'  style='width:95%'>"
                + "                  <div class='block' style='width:30%'>" + (value.DesignName == null ? " " : "<strong>" + value.DesignName + "</strong>")
                + "                  <div>" + value.Size + "</div>"
                + "                  <div>" + value.Colour + "</div>"
                + "                  </div>"
                + "                  <div class='block' style='width:20%'>" + (value.Quality == null ? " " : "<strong>" + value.Quality + "</strong>")
                + "                  </div>"
                + "                  <div class='block'  style='width:20%'>" + (value.DocNo == null ? " " : "<span title='Dim1' class='' style='font-weight:bold'>" + value.DocNo) + "</span>"
                + "                    <div> " + value.Date + " </div>"
                + "                   </div>"
                + "                  <div class='block text-right'  style='width:10%'>" + (value.Qty == null ? " " : value.Qty) + ""
                + "                   </div>"
                + "                  <div class='block text-right'  style='width:10%'>" + (value.Rate == null ? " " : value.Rate) + ""
                + "                   </div>"
                + "                  <div class='block text-right'  style='width:10%'>" + (value.Incentive == null ? " " : value.Incentive) + ""
                + "                   </div>"
                + "          </div>"
                + "  </div>"
                + "<hr style='margin-top:0px;margin-bottom:0px'/>";
            srno++;
            QtyTotal += parseFloat(value.Qty);
            AmtTotal += parseFloat(value.Qty) * parseFloat(value.AreaPerPc) * (parseFloat(value.Rate) + parseFloat(value.Incentive));
        });
        Summary += "</div>"

        $('#SummaryContent').html(Summary);
        $('#QtyTotal').html(QtyTotal);
        $('#AmtTotal').html(AmtTotal.toFixed(2));
    }


    $('#CartSum').on('hidden.bs.modal', function (e) {
        $('#SummaryContent').html("");
        $('#QtyTotal').html(0);
        $('#AmtTotal').html(0);
    })

</script>