Source/Jobs/Controllers/PurchaseIndentCancelLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Core.Common;
using Model.Models;
using Data.Models;
using Service;
using Data.Infrastructure;
using AutoMapper;
using System.Text;
using Model.ViewModel;
using System.Xml.Linq;
using PurchaseIndentCancelDocumentEvents;
using CustomEventArgs;
using DocumentEvents;
using Reports.Controllers;

namespace Jobs.Controllers
{
    [Authorize]
    public class PurchaseIndentCancelLineController : System.Web.Mvc.Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        private bool EventException = false;

        IPurchaseIndentCancelLineService _PurchaseIndentCancelLineService;
        IUnitOfWork _unitOfWork;
        IActivityLogService _ActivityLogService;
        IExceptionHandlingService _exception;

        List<string> UserRoles = new List<string>();
        ActiivtyLogViewModel LogVm = new ActiivtyLogViewModel();

        bool TimePlanValidation = true;
        string ExceptionMsg = "";
        bool Continue = true;

        public PurchaseIndentCancelLineController(IPurchaseIndentCancelLineService PurchaseIndentCancelLineService, IUnitOfWork unitOfWork, IActivityLogService aclog, IExceptionHandlingService exec)
        {
            _PurchaseIndentCancelLineService = PurchaseIndentCancelLineService;
            _unitOfWork = unitOfWork;
            _ActivityLogService = aclog;
            _exception = exec;

            UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];

            //Log Initialization
            LogVm.SessionId = 0;
            LogVm.ControllerName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
            LogVm.ActionName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
            LogVm.User = System.Web.HttpContext.Current.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        [HttpGet]
        public JsonResult Index(int id)
        {
            var p = _PurchaseIndentCancelLineService.GetPurchaseIndentCancelLineListForHeader(id);
            return Json(p, JsonRequestBehavior.AllowGet);
        }

        public ActionResult _CreateMultiple(int id)
        {
            PurchaseIndentCancelFilterViewModel vm = new PurchaseIndentCancelFilterViewModel();
            vm.PurchaseIndentCancelHeaderId = id;
            return PartialView("_Filters", vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _FilterPost(PurchaseIndentCancelFilterViewModel vm)
        {
            List<PurchaseIndentCancelLineViewModel> temp = _PurchaseIndentCancelLineService.GetPurchaseIndentLineForMultiSelect(vm).ToList();
            PurchaseIndentCancelMasterDetailModel svm = new PurchaseIndentCancelMasterDetailModel();
            svm.PurchaseIndentCancelViewModels = temp;
            return PartialView("_Results", svm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _ResultsPost(PurchaseIndentCancelMasterDetailModel vm)
        {

            int Serial = _PurchaseIndentCancelLineService.GetMaxSr(vm.PurchaseIndentCancelViewModels.FirstOrDefault().PurchaseIndentCancelHeaderId);

            bool BeforeSave = true;

            try
            {
                BeforeSave = PurchaseIndentCancelDocEvents.beforeLineSaveBulkEvent(this, new PurchaseEventArgs(vm.PurchaseIndentCancelViewModels.FirstOrDefault().PurchaseIndentCancelHeaderId), ref db);
            }
            catch (Exception ex)
            {
                string message = _exception.HandleException(ex);
                TempData["CSEXCL"] += message;
                EventException = true;
            }

            if (!BeforeSave)
                ModelState.AddModelError("", "Validation failed before save");

            if (ModelState.IsValid && BeforeSave && !EventException)
            {
                foreach (var item in vm.PurchaseIndentCancelViewModels)
                {
                    decimal balqty = (from p in db.ViewPurchaseIndentBalance
                                      where p.PurchaseIndentLineId == item.PurchaseIndentLineId
                                      select p.BalanceQty).FirstOrDefault();
                    if (balqty < item.Qty)
                    {
                        ModelState.AddModelError("", "Qty Exceeding Balance Qty");
                        return PartialView("_Results", vm);
                    }
                    if (item.Qty > 0)
                    {
                        PurchaseIndentCancelLine line = new PurchaseIndentCancelLine();

                        line.PurchaseIndentCancelHeaderId = item.PurchaseIndentCancelHeaderId;
                        line.PurchaseIndentLineId = item.PurchaseIndentLineId;
                        line.Qty = item.Qty;
                        line.CreatedDate = DateTime.Now;
                        line.ModifiedDate = DateTime.Now;
                        line.CreatedBy = User.Identity.Name;
                        line.ModifiedBy = User.Identity.Name;
                        line.ObjectState = Model.ObjectState.Added;
                        db.PurchaseIndentCancelLine.Add(line);

                        //_PurchaseIndentCancelLineService.Create(line);

                    }
                }

                PurchaseIndentCancelHeader Header = db.PurchaseIndentCancelHeader.Find(vm.PurchaseIndentCancelViewModels.FirstOrDefault().PurchaseIndentCancelHeaderId);

                if (Header.Status != (int)StatusConstants.Drafted && Header.Status != (int)StatusConstants.Import)
                {
                    Header.Status = (int)StatusConstants.Modified;
                    Header.ModifiedBy = User.Identity.Name;
                    Header.ModifiedDate = DateTime.Now;

                    Header.ObjectState = Model.ObjectState.Modified;
                    db.PurchaseIndentCancelHeader.Add(Header);
                }

                try
                {
                    PurchaseIndentCancelDocEvents.onLineSaveBulkEvent(this, new PurchaseEventArgs(vm.PurchaseIndentCancelViewModels.FirstOrDefault().PurchaseIndentCancelHeaderId), ref db);
                }
                catch (Exception ex)
                {
                    string message = _exception.HandleException(ex);
                    TempData["CSEXCL"] += message;
                    EventException = true;
                }

                try
                {
                    if (EventException)
                    { throw new Exception(); }

                    db.SaveChanges();
                    //_unitOfWork.Save();
                }

                catch (Exception ex)
                {
                    string message = _exception.HandleException(ex);
                    TempData["CSEXCL"] += message;
                    return PartialView("_Results", vm);
                }

                try
                {
                    PurchaseIndentCancelDocEvents.afterLineSaveBulkEvent(this, new PurchaseEventArgs(vm.PurchaseIndentCancelViewModels.FirstOrDefault().PurchaseIndentCancelHeaderId), ref db);
                }
                catch (Exception ex)
                {
                    string message = _exception.HandleException(ex);
                    TempData["CSEXC"] += message;
                }

                LogActivity.LogActivityDetail(LogVm.Map(new ActiivtyLogViewModel
                {
                    DocTypeId = Header.DocTypeId,
                    DocId = Header.PurchaseIndentCancelHeaderId,
                    ActivityType = (int)ActivityTypeContants.MultipleCreate,
                    DocNo = Header.DocNo,
                    DocDate = Header.DocDate,
                    DocStatus = Header.Status,
                }));

                return Json(new { success = true });

            }
            return PartialView("_Results", vm);

        }

        [HttpGet]
        public ActionResult CreateLine(int id)
        {
            return _Create(id);
        }

        [HttpGet]
        public ActionResult CreateLineAfter_Submit(int id)
        {
            return _Create(id);
        }

        public ActionResult _Create(int Id) //Id ==>Prod Order Cancel Header Id
        {
            PurchaseIndentCancelLineViewModel svm = new PurchaseIndentCancelLineViewModel();
            PurchaseIndentCancelHeader H = new PurchaseIndentCancelHeaderService(_unitOfWork).Find(Id);
            //Getting Settings
            var settings = new PurchaseIndentSettingService(_unitOfWork).GetPurchaseIndentSettingForDocument(H.DocTypeId, H.DivisionId, H.SiteId);
            svm.PurchIndentSettings = Mapper.Map<PurchaseIndentSetting, PurchaseIndentSettingsViewModel>(settings);

            svm.PurchaseIndentCancelHeaderId = Id;
            ViewBag.LineMode = "Create";
            return PartialView("_Create", svm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _CreatePost(PurchaseIndentCancelLineViewModel svm)
        {

            if (svm.PurchaseIndentCancelLineId <= 0)
            {
                ViewBag.LineMode = "Create";
            }
            else
            {
                ViewBag.LineMode = "Edit";
            }

            bool BeforeSave = true;

            try
            {

                if (svm.PurchaseIndentLineId <= 0)
                    BeforeSave = PurchaseIndentCancelDocEvents.beforeLineSaveEvent(this, new PurchaseEventArgs(svm.PurchaseIndentCancelHeaderId, EventModeConstants.Add), ref db);
                else
                    BeforeSave = PurchaseIndentCancelDocEvents.beforeLineSaveEvent(this, new PurchaseEventArgs(svm.PurchaseIndentCancelHeaderId, EventModeConstants.Edit), ref db);

            }
            catch (Exception ex)
            {
                string message = _exception.HandleException(ex);

Source/Jobs/Views/PurchaseIndentCancelLine/Delete.cshtml
@model Surya.India.Model.ViewModels.SaleOrderCancelLineViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">

        <h4>
            <span style="font-family: Calibri,sans-serif,Verdana"> Delete Sale Order Cancel Line.</span>
        </h4>

    </div>
    <div class="panel-info" style="padding-left:15px">
        <div>
            
            <dl class="dl-horizontal">
                @Html.HiddenFor(model => model.SaleOrderCancelLineId)

                <dt>
                    @Html.DisplayNameFor(model => model.DocNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DocNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ProductName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProductName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedDate)
                </dd>

            </dl>
            <hr />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary btn-sm CurveBorder" /> 
                    <span style="font-family: Calibri,sans-serif,Verdana;font-size:large">
                            @Html.ActionLink("Back", "Index", new { Id = Model.SaleOrderCancelHeaderId }, new { @class = "btn btn-primary btn-sm col-md-offset-1 CurveBorder ActionLinkPadding" })    
                    </span>
                   
                </div>
            }
        </div>
    </div>
</div>

Source/Jobs/Views/PurchaseIndentCancelLine/Index.cshtml
@model IQueryable<Surya.India.Model.ViewModels.SaleOrderCancelLineViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<span style="font-family: Calibri,sans-serif,Verdana;font-size:large">
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Create New", "Create", new { Id = ViewBag.SaleOrderCancelHeaderId })<span> &nbsp |</span>
        @Html.ActionLink("Back to List", "Index", "SaleOrderCancelHeader")
    }
    
</span>*@

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>
            <span style="font-family: Calibri,sans-serif,Verdana">Sale Order Cancel Line(CancelNo:@ViewBag.CancelNo).</span>
        </h4>
        <hr style="margin-top:0px;margin-bottom:0px" />
        <div class="panel-info">
            <span style="font-family: Calibri,sans-serif,Verdana;font-size:large;">
                <u> @Html.ActionLink("Create", "Create", new { Id = @ViewBag.SaleOrderCancelHeaderId }, new { @class = "modal-link" })</u>&nbsp;|
            </span>
            <span style="font-family: Calibri,sans-serif,Verdana;font-size:large;">
                <u> @Html.ActionLink("Back to List", "Index", "SaleOrderCancelHeader", null, new { @class = "modal-link" })</u>
            </span>

        </div>
    </div>
    <div class="panel-info" style="padding-left:5px;padding-top:2px">
        @Html.Grid(Model).Columns(columns =>
           {
               columns.Add(m => m.SaleOrderCancelLineId, true);
               columns.Add(m=>m.DocNo).Titled("Sale Order No.");
               columns.Add(m => m.BuyerName).Titled("Buyer");
               columns.Add(m=>m.ProductName).Titled("Product");
               columns.Add(m => m.Qty).Titled("Cancel Qty");
               columns.Add(m => m.LineRemark).Titled("Remark");
               columns.Add().Sanitized(false).Encoded(false).RenderValueAs(m => @Html.ActionLink(" ", "Edit", "SaleOrderCancelLine", new { id = m.SaleOrderCancelLineId }, new { @class = "rowEditBlue" })).SetWidth(20);
               columns.Add().Sanitized(false).Encoded(false).RenderValueAs(m => @Html.ActionLink(" ", "Delete", "SaleOrderCancelLine", new { id = m.SaleOrderCancelLineId }, new { @class = "rowDeleteBlue" })).SetWidth(20);
           }).WithPaging(25).EmptyText("No records found.")
    </div>
</div>

Source/Jobs/Views/PurchaseIndentCancelLine/_Filters.cshtml
@model Model.ViewModel.PurchaseIndentCancelFilterViewModel
@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Filters</span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("_FilterPost", "PurchaseIndentCancelLine", FormMethod.Post, new { enctype = "multipart/form-data", id = "modform" }))
        {

            <div class="form-horizontal modal-body">

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.PurchaseIndentCancelHeaderId)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProductId, "Product ", new { @class = "control-label col-md-4 col-sm-2 " })
                                <div class="col-md-7 col-sm-10">
                                    @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control col-xs-7 required" })
                                    @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                                    <span id="status" class="text-danger"></span>
                                </div>
                            </div>
                        </div>                                                  
                
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.PurchaseIndentId, "Purchase Indent", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.PurchaseIndentId, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.PurchaseIndentId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductGroupId, "Product Group", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductGroupId, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">
                    <button class="btn custom" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit" title="Proceed" ><span class="glyphicon glyphicon-arrow-right black"></span> </h2></button>                  
                </div>

            </div>

        }
    </div>
</div>


<script type="text/javascript">


    $(document).ready(function () {
        $("#ProductId").select2("focus");

        //CustomSelectFunction($("#ProductId"), '/ComboHelpList/GetProducts', '/ComboHelpList/SetProducts', 'Enter Product Name', true, 3);
        //CustomSelectFunction($("#PurchaseIndentId"), '/ComboHelpList/GetPurchaseIndents', '/ComboHelpList/SetPurchaseIndents', 'Enter Production Order', true, 1);
        CustomSelectFunction($("#ProductGroupId"), '/ComboHelpList/GetProductGroup', '/ComboHelpList/SetProductGroups', 'Enter Product Group Name', true, 3);


        var DocID = $('#PurchaseIndentCancelHeaderId', '.modal-body').val();
        var URL = '/PurchaseIndentCancelLine/GetPurchaseIndents/' + DocID;
        $("#PurchaseIndentId").select2({
            minimumInputLength: 0,
            multiple: true,
            ajax: {
                url: URL,
                dataType: 'json',
                type: "GET",
                quietMillis: 1000,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.DocNo,
                                id: item.PurchaseIndentHeaderId
                            }
                        })

                    };
                }
            },


        });



        var URL = '/ComboHelpList/GetCustomProducts/';
        $("#ProductId").select2({
            minimumInputLength: 1,
            multiple: true,
            ajax: {
                url: URL,
                dataType: 'json',
                type: "GET",
                quietMillis: 1000,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.PropFirst,
                                id: item.Id
                            }
                        })

                    };
                }
            },


        });

    });

</script>