Source/Jobs/Controllers/JobInvoiceLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Model.Models;
using Data.Models;
using Service;
using Data.Infrastructure;
using Core.Common;
using Model.ViewModels;
using AutoMapper;
using System.Text;
using Model.ViewModel;
using System.Xml.Linq;
using JobInvoiceDocumentEvents;
using CustomEventArgs;
using DocumentEvents;
using Reports.Controllers;
using Jobs.Helpers;
using System.Data.Entity;
namespace Jobs.Controllers
{

    [Authorize]
    public class JobInvoiceLineController : System.Web.Mvc.Controller, IDisposable
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        List<string> UserRoles = new List<string>();
        ActiivtyLogViewModel LogVm = new ActiivtyLogViewModel();

        bool TimePlanValidation = true;
        string ExceptionMsg = "";
        bool Continue = true;

        private bool EventException = false;
        IJobInvoiceLineService _JobInvoiceLineService;
        IUnitOfWork _unitOfWork;
        IExceptionHandlingService _exception;

        public JobInvoiceLineController(IJobInvoiceLineService SaleOrder, IUnitOfWork unitOfWork, IExceptionHandlingService exec)
        {
            _JobInvoiceLineService = SaleOrder;
            _unitOfWork = unitOfWork;
            _exception = exec;

            UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];

            //Log Initialization
            LogVm.SessionId = 0;
            LogVm.ControllerName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
            LogVm.ActionName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
            LogVm.User = System.Web.HttpContext.Current.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        [HttpGet]
        public JsonResult Index(int id)
        {
            //var p = _JobInvoiceLineService.GetLineListForIndex(id).ToList();
           // return Json(p, JsonRequestBehavior.AllowGet);
            var p = Json(_JobInvoiceLineService.GetLineListForIndex(id).ToList(), JsonRequestBehavior.AllowGet);
            p.MaxJsonLength = int.MaxValue;
            return p;
        }
        public ActionResult _ForReceipt(int id, int? JobworkrId)
        {
            JobInvoiceLineFilterViewModel vm = new JobInvoiceLineFilterViewModel();

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(id);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);
            vm.DocumentTypeSettings = new DocumentTypeSettingsService(_unitOfWork).GetDocumentTypeSettingsForDocument(Header.DocTypeId);

            if (JobworkrId.HasValue)
                vm.JobWorkerId = JobworkrId.Value;
            vm.JobInvoiceHeaderId = id;
            vm.JobInvoiceSettings = Mapper.Map<JobInvoiceSettingsViewModel>(Settings);
            return PartialView("_Filters", vm);
        }

        public ActionResult _ForInspection(int id, int? JobworkrId)
        {
            JobInvoiceLineFilterViewModel vm = new JobInvoiceLineFilterViewModel();

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(id);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);
            vm.DocumentTypeSettings = new DocumentTypeSettingsService(_unitOfWork).GetDocumentTypeSettingsForDocument(Header.DocTypeId);

            if (JobworkrId.HasValue)
                vm.JobWorkerId = JobworkrId.Value;
            vm.JobInvoiceHeaderId = id;
            vm.JobInvoiceSettings = Mapper.Map<JobInvoiceSettingsViewModel>(Settings);
            return PartialView("_InspectionFilters", vm);
        }

        public ActionResult _ForOrder(int id, int? JobworkrId)
        {
            JobInvoiceLineFilterViewModel vm = new JobInvoiceLineFilterViewModel();

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(id);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);
            vm.DocumentTypeSettings = new DocumentTypeSettingsService(_unitOfWork).GetDocumentTypeSettingsForDocument(Header.DocTypeId);

            if (JobworkrId.HasValue)
                vm.JobWorkerId = JobworkrId.Value;
            vm.JobInvoiceHeaderId = id;
            vm.JobInvoiceSettings = Mapper.Map<JobInvoiceSettingsViewModel>(Settings);
            return PartialView("_OrderFilters", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _FilterPost(JobInvoiceLineFilterViewModel vm)
        {
            List<JobInvoiceLineViewModel> temp = _JobInvoiceLineService.GetJobReceiptForFilters(vm).ToList();

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(vm.JobInvoiceHeaderId);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);

            JobInvoiceMasterDetailModel svm = new JobInvoiceMasterDetailModel();
            svm.JobInvoiceLineViewModel = temp;
            svm.JobInvoiceSettings = Mapper.Map<JobInvoiceSettingsViewModel>(Settings);
            return PartialView("_Results", svm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _FilterPostInspections(JobInvoiceLineFilterViewModel vm)
        {
            List<JobInvoiceLineViewModel> temp = _JobInvoiceLineService.GetJobInspectionForFilters(vm).ToList();

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(vm.JobInvoiceHeaderId);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);

            JobInvoiceMasterDetailModel svm = new JobInvoiceMasterDetailModel();
            svm.JobInvoiceLineViewModel = temp;
            svm.JobInvoiceSettings = Mapper.Map<JobInvoiceSettingsViewModel>(Settings);
            return PartialView("_Results", svm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _FilterPostOrders(JobInvoiceLineFilterViewModel vm)
        {
            List<JobInvoiceLineViewModel> temp = _JobInvoiceLineService.GetJobOrderForFilters(vm).ToList();
            JobInvoiceMasterDetailModel svm = new JobInvoiceMasterDetailModel();
            svm.JobInvoiceLineViewModel = temp;
            return PartialView("_OrderResults", svm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _ResultsPost(JobInvoiceMasterDetailModel vm)
        {
            List<JobInvoiceLine> Lines = new List<JobInvoiceLine>();
            List<JobInvoiceLineStatus> LineStat = new List<JobInvoiceLineStatus>();
            List<HeaderChargeViewModel> HeaderCharges = new List<HeaderChargeViewModel>();
            List<LineChargeViewModel> LineCharges = new List<LineChargeViewModel>();
            int pk = 0;
            Dictionary<int, decimal> LineStatus = new Dictionary<int, decimal>();
            List<LineReferenceIds> RefIds = new List<LineReferenceIds>();
            db.Configuration.AutoDetectChangesEnabled = false;

            int Serial = _JobInvoiceLineService.GetMaxSr(vm.JobInvoiceLineViewModel.FirstOrDefault().JobInvoiceHeaderId);
            bool HeaderChargeEdit = false;

            JobInvoiceHeader Header = new JobInvoiceHeaderService(_unitOfWork).Find(vm.JobInvoiceLineViewModel.FirstOrDefault().JobInvoiceHeaderId);

            JobInvoiceSettings Settings = new JobInvoiceSettingsService(_unitOfWork).GetJobInvoiceSettingsForDocument(Header.DocTypeId, Header.DivisionId, Header.SiteId);

            int? MaxLineId = new JobInvoiceLineChargeService(_unitOfWork).GetMaxProductCharge(Header.JobInvoiceHeaderId, "Web.JobInvoiceLines", "JobInvoiceHeaderId", "JobInvoiceLineId");

            int PersonCount = 0;
            if (!Settings.CalculationId.HasValue)
            {
                throw new Exception("Calculation not configured in purchase order settings");
            }

            int CalculationId = Settings.CalculationId ?? 0;

            List<LineDetailListViewModel> LineList = new List<LineDetailListViewModel>();


            bool BeforeSave = true;
            try
            {
                BeforeSave = JobInvoiceDocEvents.beforeLineSaveBulkEvent(this, new JobEventArgs(vm.JobInvoiceLineViewModel.FirstOrDefault().JobInvoiceHeaderId), ref db);
            }
            catch (Exception ex)
            {
                string message = _exception.HandleException(ex);
                TempData["CSEXCL"] += message;
                EventException = true;
            }

            if (!BeforeSave)
                ModelState.AddModelError("", "Validation failed before save");


            if (ModelState.IsValid && BeforeSave && !EventException)
            {
                try
                {
                    foreach (var item in vm.JobInvoiceLineViewModel)
                    {
                        if (item.DealQty > 0 && item.Rate > 0)
                        {
                            JobInvoiceLine line = new JobInvoiceLine();
                            //var receipt = new JobGoodsReceiptLineService(_unitOfWork).Find(item.JobGoodsReceiptLineId );
                            line.JobInvoiceHeaderId = item.JobInvoiceHeaderId;
                            line.JobReceiveLineId = item.JobReceiveLineId;
                            line.UnitConversionMultiplier = item.UnitConversionMultiplier;
                            //line.Remark = receipt.Remark;

Source/Jobs/Views/JobInvoiceLine/_Filters.cshtml
@model Model.ViewModel.JobInvoiceLineFilterViewModel
@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Filters</span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("_FilterPost", "JobInvoiceLine", FormMethod.Post, new { enctype = "multipart/form-data", id = "modform" }))
        {

            <div class="form-horizontal modal-body">

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.JobInvoiceHeaderId)
                @Html.HiddenFor(m => m.JobWorkerId)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReceiveFromDate, "From Date", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(m => m.ReceiveFromDate, "{0:dd/MMMM/yyyy}", new { @class = "datepicker form-control required" })
                                @Html.ValidationMessageFor(model => model.ReceiveFromDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReceiveToDate, "To Date", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(m => m.ReceiveToDate, "{0:dd/MMMM/yyyy}", new { @class = "datepicker form-control required" })
                                @Html.ValidationMessageFor(model => model.ReceiveToDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobReceiveHeaderId, (Model.DocumentTypeSettings.ContraDocTypeCaption ?? "Receive No."), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ContraDocTypeCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.JobReceiveHeaderId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.JobReceiveHeaderId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="display:@(Model.JobInvoiceSettings.isVisibleHeaderJobWorker ? "none" : "")">
                        @Html.HiddenFor(m => m.JobInvoiceSettings.isVisibleHeaderJobWorker)
                        @Html.HiddenFor(m => m.DocumentTypeSettings.PartyCaption)
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobWorkerIds, (Model.DocumentTypeSettings.PartyCaption ?? "Party"), new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.JobWorkerIds, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.JobWorkerIds, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductId, (Model.DocumentTypeSettings.ProductCaption ?? "Product"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                                <span id="status" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductGroupId, (Model.DocumentTypeSettings.ProductGroupCaption ?? "Product Group"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductGroupCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductGroupId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductCategoryId, (Model.DocumentTypeSettings.ProductCategoryCaption ?? "Product Category"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductCategoryCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductCategoryId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductCategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">
                    <button class="btn custom" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit" title="Proceed"><span class="glyphicon glyphicon-arrow-right black"></span> </h2></button>
                </div>

            </div>

        }
    </div>
</div>


<script type="text/javascript">


    $(document).ready(function () {
      
        var ProcessId = '@Model.JobInvoiceSettings.ProcessId';
        var DocID = $('#JobInvoiceHeaderId', '.modal-body').val();
        CustomSelectFunction($("#ProductCategoryId"), '/ComboHelpList/GetProductCategory', '/ComboHelpList/SetProductCategory', ' ', true, 1);
        CustomSelectFunction($("#ProductGroupId"), '/ComboHelpList/GetProductGroup', '/ComboHelpList/SetProductGroup', ' ', true, 1);
        CustomSelectFunction($("#JobWorkerIds"), '/ComboHelpList/GetJobWorkersWithProcess', '/ComboHelpList/SetJobworkers', ' ', true, 1, ProcessId);

        $('.datepicker').datepicker({
            format: 'dd/MM/yyyy',
            "setDate": new Date(),
            "autoclose": true
        })


        var URL = '/JobInvoiceLine/GetPendingJobReceiveProducts/' + DocID;
        $("#ProductId").select2({
            minimumInputLength: 1,
            multiple: true,
            ajax: {
                url: URL,
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.PropFirst,
                                id: item.Id
                            }
                        })

                    };
                }
            },


        });


        var URLJO = '/JobInvoiceLine/GetPendingJobReceive/' + DocID;
        $("#JobReceiveHeaderId").select2({
            minimumInputLength: 1,
            multiple: true,
            ajax: {
                url: URLJO,
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.PropFirst,
                                id: item.Id
                            }
                        })

                    };
                }
            },


        });



    });

</script>

Source/Jobs/Views/JobInvoiceLine/_InspectionFilters.cshtml
@model Model.ViewModel.JobInvoiceLineFilterViewModel
@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Filters</span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("_FilterPostInspections", "JobInvoiceLine", FormMethod.Post, new { enctype = "multipart/form-data", id = "modform" }))
        {

            <div class="form-horizontal modal-body">

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.JobInvoiceHeaderId)
                @Html.HiddenFor(m => m.JobWorkerId)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReceiveFromDate, "From Date", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(m => m.ReceiveFromDate, "{0:dd/MMMM/yyyy}", new { @class = "datepicker form-control required" })
                                @Html.ValidationMessageFor(model => model.ReceiveFromDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReceiveToDate, "To Date", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(m => m.ReceiveToDate, "{0:dd/MMMM/yyyy}", new { @class = "datepicker form-control required" })
                                @Html.ValidationMessageFor(model => model.ReceiveToDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobReceiveHeaderId, (Model.DocumentTypeSettings.ContraDocTypeCaption ?? "Receive No."), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ContraDocTypeCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.JobReceiveHeaderId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.JobReceiveHeaderId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="display:@(Model.JobInvoiceSettings.isVisibleHeaderJobWorker ? "none" : "")">
                        @Html.HiddenFor(m => m.JobInvoiceSettings.isVisibleHeaderJobWorker)
                        @Html.HiddenFor(m => m.DocumentTypeSettings.PartyCaption)
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobWorkerIds, (Model.DocumentTypeSettings.PartyCaption ?? "Party"), new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.JobWorkerIds, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.JobWorkerIds, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductId, (Model.DocumentTypeSettings.ProductCaption ?? "Product"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                                <span id="status" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductGroupId, (Model.DocumentTypeSettings.ProductGroupCaption ?? "Product Group"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductGroupCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductGroupId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductCategoryId, (Model.DocumentTypeSettings.ProductCategoryCaption ?? "Product Category"), new { @class = "control-label col-md-4 col-sm-2" })
                            @Html.HiddenFor(m => m.DocumentTypeSettings.ProductCategoryCaption)
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductCategoryId, new { @class = "form-control required" })
                                @Html.ValidationMessageFor(model => model.ProductCategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">
                    <button class="btn custom" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit" title="Proceed"><span class="glyphicon glyphicon-arrow-right black"></span> </h2></button>
                </div>

            </div>

        }
    </div>
</div>


<script type="text/javascript">


    $(document).ready(function () {
      
        var ProcessId = '@Model.JobInvoiceSettings.ProcessId';
        var DocID = $('#JobInvoiceHeaderId', '.modal-body').val();
        CustomSelectFunction($("#ProductCategoryId"), '/ComboHelpList/GetProductCategory', '/ComboHelpList/SetProductCategory', ' ', true, 1);
        CustomSelectFunction($("#ProductGroupId"), '/ComboHelpList/GetProductGroup', '/ComboHelpList/SetProductGroup', ' ', true, 1);
        CustomSelectFunction($("#JobWorkerIds"), '/ComboHelpList/GetJobWorkersWithProcess', '/ComboHelpList/SetJobworkers', ' ', true, 1, ProcessId);

        $('.datepicker').datepicker({
            format: 'dd/MM/yyyy',
            "setDate": new Date(),
            "autoclose": true
        })


        var URL = '/JobInvoiceLine/GetPendingJobReceiveProducts/' + DocID;
        $("#ProductId").select2({
            minimumInputLength: 1,
            multiple: true,
            ajax: {
                url: URL,
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.PropFirst,
                                id: item.Id
                            }
                        })

                    };
                }
            },


        });


        var URLJO = '/JobInvoiceLine/GetPendingJobReceive/' + DocID;
        $("#JobReceiveHeaderId").select2({
            minimumInputLength: 1,
            multiple: true,
            ajax: {
                url: URLJO,
                dataType: 'json',
                type: "GET",
                quietMillis: 500,
                data: function (term) {
                    return {
                        term: term,
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.PropFirst,
                                id: item.Id
                            }
                        })

                    };
                }
            },


        });



    });

</script>