Source/Jobs/Areas/Rug/Controllers/CostingHeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Core.Common;
using Model.Models;
using Data.Models;
using Model.ViewModels;
using Service;
using Jobs.Helpers;
using Data.Infrastructure;
using Presentation.ViewModels;
using AutoMapper;
using Presentation;
using System.Text;
using EmailContents;
using Model.ViewModel;
using System.Xml.Linq;
using Reports.Controllers;
using Reports.Reports;
using System.Configuration;

namespace Jobs.Areas.Rug.Controllers
{
    [Authorize]
    public class CostingHeaderController : System.Web.Mvc.Controller
    {

        private ApplicationDbContext context = new ApplicationDbContext();        

        List<string> UserRoles = new List<string>();
        ActiivtyLogViewModel LogVm = new ActiivtyLogViewModel();

        bool TimePlanValidation = true;
        string ExceptionMsg = "";
        bool Continue = true;

        ICostingHeaderService _CostingHeaderService;
        IUnitOfWork _unitOfWork;
        IExceptionHandlingService _exception;
        public CostingHeaderController(ICostingHeaderService PurchaseOrderHeaderService, IActivityLogService ActivityLogService, IUnitOfWork unitOfWork, IExceptionHandlingService exec)
        {
            _CostingHeaderService = PurchaseOrderHeaderService;
            _unitOfWork = unitOfWork;
            _exception = exec;

            UserRoles = (List<string>)System.Web.HttpContext.Current.Session["Roles"];

            //Log Initialization
            LogVm.SessionId = 0;
            LogVm.ControllerName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
            LogVm.ActionName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
            LogVm.User = System.Web.HttpContext.Current.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        public ActionResult DocumentTypeIndex(int id)//DocumentCategoryId
        {
            var p = new DocumentTypeService(_unitOfWork).FindByDocumentCategory(id).ToList();

            if (p != null)
            {
                if (p.Count == 1)
                    return RedirectToAction("Index", new { id = p.FirstOrDefault().DocumentTypeId });
            }

            return View("DocumentTypeList", p);
        }

        // GET: /CostingHeader/

        public ActionResult Index(int id, string IndexType)//DocumentTypeId
        {
            if (IndexType == "PTS")
            {
                return RedirectToAction("Index_PendingToSubmit", new { id });
            }
            else if (IndexType == "PTR")
            {
                return RedirectToAction("Index_PendingToReview", new { id });
            }
            IQueryable<CostingHeaderIndexViewModel> p = _CostingHeaderService.GetCostingHeaderList(id, User.Identity.Name);
            PrepareViewBagSettings(id);
            ViewBag.PendingToSubmit = PendingToSubmitCount(id);
            ViewBag.PendingToReview = PendingToReviewCount(id);
            ViewBag.IndexStatus = "All";
            return View(p);
        }

        public ActionResult Index_PendingToSubmit(int id)
        {
            var PendingToSubmit = _CostingHeaderService.GetCostingHeaderListPendingToSubmit(id, User.Identity.Name);
            PrepareViewBagSettings(id);
            ViewBag.PendingToSubmit = PendingToSubmitCount(id);
            ViewBag.PendingToReview = PendingToReviewCount(id);
            ViewBag.IndexStatus = "PTS";
            return View("Index", PendingToSubmit);
        }

        public ActionResult Index_PendingToReview(int id)
        {
            var PendingtoReview = _CostingHeaderService.GetCostingHeaderListPendingToReview(id, User.Identity.Name);
            PrepareViewBagSettings(id);
            ViewBag.PendingToSubmit = PendingToSubmitCount(id);
            ViewBag.PendingToReview = PendingToReviewCount(id);
            ViewBag.IndexStatus = "PTR";
            return View("Index", PendingtoReview);
        }


        private void PrepareViewBagSettings(int id)
        {
            ViewBag.Name = new DocumentTypeService(_unitOfWork).Find(id).DocumentTypeName;
            ViewBag.id = id;
            var DivisionId = (int)System.Web.HttpContext.Current.Session["DivisionId"];
            var SiteId = (int)System.Web.HttpContext.Current.Session["SiteId"];
            //var settings = new CostingSettingsService(_unitOfWork).GetCostingSettings(id, DivisionId, SiteId);
            ViewBag.AdminSetting = UserRoles.Contains("Admin").ToString();
            //if (settings != null)
            //{
            //    ViewBag.ImportMenuId = settings.ImportMenuId;
            //    ViewBag.SqlProcDocumentPrint = settings.SqlProcDocumentPrint;
            //    ViewBag.ExportMenuId = settings.ExportMenuId;
            //}

        }


        [HttpGet]
        public ActionResult NextPage(int DocId, int DocTypeId)//CurrentHeaderId
        {
            var nextId = new NextPrevIdService(_unitOfWork).GetNextPrevId(DocId, DocTypeId, User.Identity.Name, "", "Web.CostingHeaders", "CostingHeaderId", PrevNextConstants.Next);
            return Edit(nextId, "");
        }
        [HttpGet]
        public ActionResult PrevPage(int DocId, int DocTypeId)//CurrentHeaderId
        {
            var PrevId = new NextPrevIdService(_unitOfWork).GetNextPrevId(DocId, DocTypeId, User.Identity.Name, "", "Web.CostingHeaders", "CostingHeaderId", PrevNextConstants.Prev);
            return Edit(PrevId, "");
        }

        [HttpGet]
        public ActionResult History()
        {
            //To Be Implemented
            //return View("~/Views/Shared/UnderImplementation.cshtml");
            MultipleDocumentPrint rvm = new MultipleDocumentPrint()
            {
                // id = 5,
            };
            return PartialView("MultipleDocumentPrint", rvm);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult History(MultipleDocumentPrint vm)
        {
            ApplicationDbContext Db = new ApplicationDbContext();
            String query = Db.strSchemaName + ".ProcCostingPrint " + 3.ToString();
            //string PackingId = (vm.CostingHeaderId.ToString());
            //String query = Db.strSchemaName + ".ProcCostingPrintToMultiple '" + PackingId.ToString() + "'";
            String ReportTitle = "Sale Order";
            return RedirectToAction("DocumentPrint", "Report_DocumentPrint", new { queryString = query, ReportTitle = ReportTitle });
        }

        [HttpGet]
        public ActionResult Email()
        {
            //To Be Implemented
            return View("~/Views/Shared/UnderImplementation.cshtml");
        }

        [HttpGet]
        public ActionResult Report(int id)
        {
            DocumentType Dt = new DocumentType();
            Dt = new DocumentTypeService(_unitOfWork).Find(id);

            Dictionary<int, string> DefaultValue = new Dictionary<int, string>();

            //if (!Dt.ReportMenuId.HasValue)
            //    throw new Exception("Report Menu not configured in document types");

            if (!Dt.ReportMenuId.HasValue)
                return Redirect((string)System.Configuration.ConfigurationManager.AppSettings["JobsDomain"] + "/GridReport/GridReportLayout/?MenuName=Sale Order Report&DocTypeId=" + id.ToString());


            Model.Models.Menu menu = new MenuService(_unitOfWork).Find(Dt.ReportMenuId ?? 0);

            if (menu != null)
            {
                ReportHeader header = new ReportHeaderService(_unitOfWork).GetReportHeaderByName(menu.MenuName);

                ReportLine Line = new ReportLineService(_unitOfWork).GetReportLineByName("DocumentType", header.ReportHeaderId);
                if (Line != null)
                    DefaultValue.Add(Line.ReportLineId, id.ToString());
                ReportLine Site = new ReportLineService(_unitOfWork).GetReportLineByName("Site", header.ReportHeaderId);
                if (Site != null)
                    DefaultValue.Add(Site.ReportLineId, ((int)System.Web.HttpContext.Current.Session["SiteId"]).ToString());
                ReportLine Division = new ReportLineService(_unitOfWork).GetReportLineByName("Division", header.ReportHeaderId);
                if (Division != null)
                    DefaultValue.Add(Division.ReportLineId, ((int)System.Web.HttpContext.Current.Session["DivisionId"]).ToString());

            }

            TempData["ReportLayoutDefaultValues"] = DefaultValue;

            return Redirect((string)System.Configuration.ConfigurationManager.AppSettings["JobsDomain"] + "/Report_ReportPrint/ReportPrint/?MenuId=" + Dt.ReportMenuId);

        }

        [HttpGet]
        public ActionResult Remove()
        {
            //To Be Implemented
            return View("~/Views/Shared/UnderImplementation.cshtml");
        }

        private void PrepareViewBag(CostingHeaderIndexViewModel s)
        {


            ViewBag.UnitConvForList = (from p in context.UnitConversonFor
                                       select p).ToList();
            ViewBag.Name = new DocumentTypeService(_unitOfWork).Find(s.DocTypeId).DocumentTypeName;
            ViewBag.id = s.DocTypeId;
            //ViewBag.DivisionList = new DivisionService(_unitOfWork).GetDivisionList().ToList();            
            ViewBag.ShipMethodList = new ShipMethodService(_unitOfWork).GetShipMethodList().ToList();
            ViewBag.DeliveryTermsList = new DeliveryTermsService(_unitOfWork).GetDeliveryTermsList().ToList();
            ViewBag.BuyerList = new BuyerService(_unitOfWork).GetBuyerList().ToList();
            ViewBag.CurrencyList = new CurrencyService(_unitOfWork).GetCurrencyList().ToList();
            //ViewBag.SiteList = new SiteService(_unitOfWork).GetSiteList().ToList();
            //List<SelectListItem> temp = new List<SelectListItem>();

Source/Jobs/Areas/Rug/Views/CostingHeader/Delete.cshtml
@model Model.ViewModels.SaleOrderHeaderIndexViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>
            <span style="font-family: Calibri,sans-serif,Verdana"> Delete Sale Order.</span>
        </h4>
    </div>
    @Html.HiddenFor(m=>m.DocNo)
    <div class="panel-info" style="padding-left:15px">
        <div>            
            <dl class="dl-horizontal" style="margin-top:15px">
                <dt>
                    @Html.DisplayNameFor(model => model.DocNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DocNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DocDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DocDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DivisionName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DivisionName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BuyerOrderNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BuyerOrderNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedDate)
                </dd>

            </dl>
            <hr />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="Redirect" id="Redirect" value="@ViewBag.Redirect" />
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn-primary xxlarge" /> 
                    <span style="font-family: Calibri,sans-serif,Verdana;font-size:large">
                        |@Html.ActionLink("Back to List", "Index")
                    </span>
                </div>
            }
        </div>
    </div>
</div>

Source/Jobs/Areas/Rug/Views/CostingHeader/DocumentTypeList.cshtml
@model IEnumerable<Model.Models.DocumentType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-list black"></span> Document Type List</span>
        </h3>
        
    </div>
    <div class="panel-info" style="width:100%">
        <div class="Wrapper">

            @foreach (var item in Model)
            {

                string Dd = (System.Configuration.ConfigurationManager.AppSettings["DocTypePic"]);
                string Ad = (System.Configuration.ConfigurationManager.AppSettings["AlphabetPic"]);
                string ImgSrc = Dd + item.ImageFileName;
                int val;
                bool IsNumeric = Int32.TryParse(item.DocumentTypeName.Substring(0, 1), out val);
                string ImgAlt = Ad + (IsNumeric ? "N" : item.DocumentTypeName.Substring(0, 1)) + ".png";

                <div class="Box">
                    <a href="/SaleOrderHeader/Index/@item.DocumentTypeId">
                        <div class="InnerContent">
                            <div style="width:100%;height:100%;margin-left:auto;margin-right:auto">
                                <img src="@ImgSrc" style="max-height:100%;max-width:100%;padding:5px;height:135px;width:155px; border-radius:10%" alt="@ImgAlt" onerror="this.src = '@ImgAlt'" />
                            </div>
                            <div class="titleBox">@(string.IsNullOrEmpty(item.IconDisplayName) ? item.DocumentTypeName : item.IconDisplayName)</div>
                        </div>
                    </a>
                </div>
            }           

        </div>

    </div>
</div> 

Source/Jobs/Areas/Rug/Views/CostingHeader/Index.cshtml
@using Core.Common;
@using Model.ViewModels;
@using GridMvc.Html;
@model IQueryable<Model.ViewModels.CostingHeaderIndexViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string ControllerName = (string)ViewContext.RouteData.Values["controller"];
    string IndexStatus = (string)ViewBag.IndexStatus;
}

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-list black"></span> @ViewBag.Name List</span>
        </h3>
        <hr style="margin-top:0px;margin-bottom:0px" />
        <input type="hidden" class="DocType_Id" value="@ViewBag.id">
        <div class="panel-info">
            @*<h4 style="padding:5px 0 0 0;margin:0px">
                @Html.ActionLink(" ", " ", " ", null, new { @class = "glyphicon glyphicon-refresh toolbar", @title = "Refresh Page", @data_toggle = "tooltip", @id = "RefreshPage" })
                @Html.ActionLink(" ", "Create", "CostingHeader", new { @id = @ViewBag.id }, new { @class = "glyphicon glyphicon-plus toolbar", @title = "Add New", @data_toggle = "tooltip" })
                @Html.ActionLink(" ", "GetHistory", "LogHistory", null, new { @class = "glyphicon glyphicon-user toolbar", @title = "History", @data_toggle = "tooltip", @id = "DocHistoryI" })
                @Html.ActionLink(" ", "GeneratePrints", "CostingHeader", null, new { @class = "glyphicon glyphicon-print toolbar", @title = "Print", @data_toggle = "tooltip", @id = "PrintRecordI", target = "_blank" })
                @Html.ActionLink(" ", "Remove", "CostingHeader", null, new { @class = "glyphicon glyphicon-trash toolbar", @title = "Delete", @data_toggle = "tooltip", @id = "DeleteRecord", @data_modalDelete = "" })
                @Html.ActionLink(" ", "AttachDocument", "DocumentAttachment", null, new { @class = "glyphicon glyphicon-paperclip toolbar", @title = "Attach", @data_toggle = "tooltip", @id = "AttachDocument", @data_modaltrigger = "DocumentAttachment" })
                @Html.ActionLink(" ", "Report", "CostingHeader", new { @id = @ViewBag.id }, new { @class = "glyphicon glyphicon-stats toolbar right", @title = "Report", @data_toggle = "tooltip", @id = "ReportRecord", target = "_blank" })
                @Html.ActionLink(" ", "Create", "CostingSettings", new { @id = @ViewBag.id }, new { @class = "glyphicon glyphicon-cog toolbar right", @title = "Default Settings", @data_toggle = "tooltip" })
                @Html.ActionLink(" ", "Import", "CostingHeader", new { @id = @ViewBag.id }, new { @class = "glyphicon glyphicon-import toolbar right", @title = "Import", @data_toggle = "tooltip" })
                @Html.ActionLink(" ", "", "", null, new { @class = "glyphicon glyphicon-export toolbar right", @title = "Export", @data_toggle = "tooltip" })
            </h4>*@
            <div class="btn-group">
                @Html.ActionLink(" ", "Create", "CostingHeader", new { @id = @ViewBag.id }, new { @class = "cbtn btn-circle glyphicon glyphicon-plus toolbar", @title = "Add New", @data_toggle = "tooltip" })
                @if (ViewBag.SqlProcDocumentPrint != null)
                {
                @Html.ActionLink(" ", "GeneratePrints", "CostingHeader", null, new { @class = "cbtn btn-circle glyphicon glyphicon-print toolbar", @title = "Print", @data_toggle = "tooltip", @id = "PrintRecordI", target = "_blank" })               
                }
                @Html.ActionLink(" ", "AttachDocument", "DocumentAttachment", null, new { @class = "cbtn btn-circle glyphicon glyphicon-paperclip toolbar", @title = "Attach", @data_toggle = "tooltip", @id = "AttachDocument", @data_modaltrigger = "DocumentAttachment" })
                @Html.ActionLink(" ", "Remove", "CostingHeader", null, new { @class = "cbtn btn-circle glyphicon glyphicon-trash toolbar", @title = "Delete", @data_toggle = "tooltip", @id = "DeleteRecord", @data_modalDelete = "" })
            </div>
            <div class="btn-group">
                <a class="cbtn btn-circle glyphicon glyphicon-option-horizontal dropdown-toggle" title="More Option" aria-expanded="false" style="padding-top: 6px;padding-bottom: 6px;" href="#" data-toggle="dropdown" id="dropdownMenu1">
                </a>
                <ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
                    @if (ViewBag.ExportMenuId !=null)
                    {
                    <li><a href="@Url.Action("Export", "CostingHeader", new { @id = @ViewBag.id })"><span class="glyphicon glyphicon-export"> </span>&nbsp;&nbsp;Export</a></li>
                    }
                    @if (ViewBag.ImportMenuId !=null)
                    {
                    <li><a href="@Url.Action("Import", "CostingHeader", new { @id = @ViewBag.id })"><span class="glyphicon glyphicon-import"> </span>&nbsp;&nbsp;Import</a></li>
                    }
                    @if (ViewBag.AdminSetting == "True")
                    {
                    <li><a href="@Url.Action("Create", "CostingSettings", new { @id = @ViewBag.id })"><span class="glyphicon glyphicon-cog"> </span>&nbsp;&nbsp;Settings</a></li>
                    }
                    <li role="separator" class="divider"></li>
                    <li><a id="DocHistoryI" href="@Url.Action("GetHistory", "LogHistory", new {  })"><span class="glyphicon glyphicon-user"> </span> History</a></li>
                    <li><a target="_blank" href="@Url.Action("Report", "CostingHeader", new { @ViewBag.id })"><span class="glyphicon glyphicon-stats"> </span> Report</a></li>
                       </ul>
            </div>
            <div class="btn-group right">
                @CustomHelpers.RenderIconStatusFilters(ViewBag.PendingToSubmit, ViewBag.PendingToReview, ControllerName, ViewBag.id, ViewBag.IndexStatus)
            </div>
        </div>
        @*<hr style="margin-top: 5px; margin-bottom: 5px; border-top: 1px solid #706f6f; " />

       @CustomHelpers.RenderStatusFilters(ViewBag.PendingToSubmit, ViewBag.PendingToReview, ControllerName, ViewBag.id, ViewBag.IndexStatus)*@
    </div>

    <div class="panel-info" style="padding-left:5px;padding-top:2px;font-size:12px">
        @Html.Grid(Model).Columns(columns =>
           {
               columns.Add(m => m.CostingHeaderId, true).Css("Header_Id");
               columns.Add(m => m.Status, true);
               columns.Add().Encoded(false).Sanitized(false).SetWidth("5%").RenderValueAs(m => CustomHelpers.RenderCheckBox());
               columns.Add(foo => foo.DocDate).Sortable(true).Titled("Costing Date").Format("{0:dd/MMM/yyyy}").Filterable(true);
               columns.Add(m => m.DocNo).Sortable(true).Titled("Costing No.").Filterable(true).Sortable(true);
               columns.Add(m => m.PersonName).Titled("Person").Filterable(true).Sortable(true);
               columns.Add(m => m.Remark).Sortable(true).Filterable(true).Titled("Remark");
               columns.Add().Sanitized(false).Encoded(false).RenderValueAs(m => CustomHelpers.RenderStatus(m.Status)).Titled("Status");
               columns.Add().Titled("").Encoded(false).Sanitized(false).RenderValueAs(m => CustomHelpers.RenderUserImage(m.ModifiedBy)).Titled("User").SetWidth("5%").Css("UserImageIndex");
               columns.Add().Encoded(false).Sanitized(false).RenderValueAs(m => CustomHelpers.RenderActionColumn(ControllerName, m.CostingHeaderId, m.Status, m.Reviewed, m.ReviewCount, (string)ViewBag.IndexStatus)).SetWidth(20).Css("icon-Cus-Size");
               columns.Add(true).RenderValueAs(m => CustomHelpers.RenderHEDActionLink(ControllerName, m.CostingHeaderId, m.Status, IndexStatus));
           }).WithPaging(25).EmptyText("No records found.").Sortable().Filterable().WithMultipleFilters()
    </div>
</div>

Source/Jobs/Areas/Rug/Views/CostingHeader/MultipleDocumentPrint.cshtml
@model Presentation.ViewModels.MultipleDocumentPrint


@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Please select Records to Print </span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("History", "SaleOrderHeader", FormMethod.Post, new { @class = "modal-form", id = "modform" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal modal-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SaleOrderHeaderId, new { @class = "control-label col-xs-4" })
                                <div class="col-xs-6">
                                    <input type='hidden' name='SaleOrderHeaderId' id='SaleOrderHeaderId' class="form-control col-xs-6" />
                                    @Html.ValidationMessageFor(model => model.SaleOrderHeaderId)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">                    
                    <button class="btn custom left" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit"><span class="glyphicon glyphicon-print toolbar"></span> </h2></button>
                </div>
            </div>
        }
    </div>
</div>


<script>
    $(document).ready(function () {



        CustomSelectFunction($("#SaleOrderHeaderId"), '/ComboHelpList/GetSaleOrders', '/ComboHelpList/SetSaleOrders', ' ', true, 0);


    });
</script>




<script>

    var SOarr = [];

    $("#Print").click(function () {
        //For Passing Ids String


        $("#SaleOrderHeaderId").val($('#SaleOrderHeaderId').select2("val"));


        //For Passing Parameter Names String for multi select text boxes





        var products = (JSON.stringify($('#SaleOrderHeaderId').select2('data')));
        var obj = jQuery.parseJSON(products);
        $.each(obj, function (key, value) {
            SOarr.push(value.text);
        });
        $("#SaleOrder").val(SOarr);





    });
</script>

Source/Jobs/Areas/Rug/Views/CostingHeader/_Reason.cshtml
@model Presentation.ViewModels.ReasonViewModel


@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Please specify a reason for deleting</span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("Delete", "CostingHeader", FormMethod.Post, new { @class = "modal-form", id = "modform", data_pageReload = "true" }))
        {
            @Html.ValidationLog((string)TempData["CSEXC"])
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m=>m.id)

            <div class="form-horizontal modal-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">

                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Reason, "Reason", new { @class = "control-label col-xs-2 " })
                            <div class="col-xs-9">
                                @Html.TextAreaFor(m => m.Reason, 4, 2, new { @class = "form-control col-xs-9 required" })
                                @Html.ValidationMessageFor(m => m.Reason, "", new { @class="text-danger"})
                            </div>
                        </div>
                        <script>
                            $('#Reason').focus();
                        </script>

                    </div>
                </div>
                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">                    
                    <button class="btn custom left" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit"><span class="glyphicon glyphicon-trash black"></span> </h2></button>
                </div>
            </div>
        }
    </div>
</div>